### ISSUE TITLE
Report evaluator status

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#480]
We want to have a web monitoring console for the evaluator (#479), but we want something short-term.

Idea: as each task starts and stops, write the current status to a YAML file:

``` yaml
summary:
  total: 429
  completed: 37
  active: 4
running_tasks:
- algorithm: Foo
  dataset: Bar
  started: time
  running_for: 394
  thread: graph-executor-13
```

Should look at using Guava's `EventBus` to connect the listneer (and the web listener) to the tasks.

We might also want to add some support to the CLI (#448) to deal with these files, or extract the data directly from the evaluator process.
