### ISSUE TITLE
Implement multiple data file description format

### ISSUE THREAD

**Issue by mdekstrand** [lenskit/lenskit#539]
With #517 and its related DAO coming, as well as #533, it seems useful to have the ability to read data from a descriptor file that points to other text files full of data. For example a YAML file:

```yaml
events:
    file: ratings.csv
    delimiter: ","
    type: Rating
users: users.lst
items: items.lst
```

We could then extend it to allow multiple events files, and run them into a multiplexing DAO that concatenates the event lists.
